=== cubis182/Vocab-Study/vocab.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is the structure of each node. There aren't any attributes, but only text values.
 <root>
    <entry>
        <term></term>
        <def></def>
    </entry>
</root>
 Create a schema for this if you can-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
    <xs:element name="root">
        <xs:complexType>
        <xs:choice>
            <xs:element name="entry" maxOccurs="unbounded">
            <xs:complexType>
                <xs:all>
                    
                    <xs:element name="term" type="xs:string"/>
                    <xs:element name="def" type="xs:string"/>
                </xs:all>
                 <xs:attribute name="creationDate" type="xs:date"/>
                 <xs:attribute name="lastViewed" type="xs:date"/>
                 <xs:attribute name="n" use="required"/>
                 
            </xs:complexType>
        </xs:element>
        </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cubis182/Vocab-Study/dict.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vocab.xsd">
    <entry creationDate="2025-10-18" n="9" language="unspecif">
        <term>excogito, excogitare</term>
        <def>"ad haec igitur cogita, mi Attice, vel potius excogita" (id est, cogita dum solutio inveniatur)</def>
    </entry>
    <entry creationDate="2025-10-19" n="10" language="unspecif">
        <term>se&#772;mentis, se&#772;mentis, f.</term>
        <def>same as satio</def>
    </entry>
    <entry creationDate="2025-10-20" n="12" language="unspecif">
        <term>conscribo, conscribere...</term>
        <def>scribendo colligere, litteris mandare. litteris implere, constituere,</def>
    </entry>
    <entry creationDate="2025-10-20" n="12" language="unspecif">
        <term>refragor, refragari...</term>
        <def>= opp. suffragari, id est, non suffragari, reprehendere, improbare. non adsentiri</def>
    </entry>
    <entry creationDate="2025-10-21" n="12" language="unspecif">
        <term>fasciamentum, -i, n.</term>
        <def>bandage, binding cloth</def>
    </entry>
    <entry creationDate="2025-10-25" n="13" language="unspecif">
        <term>neutiquam</term>
        <def>idem quod nequaquam</def>
    </entry>
    <entry creationDate="2025-11-08" n="14" language="unspecif">
        <term>fibra, fibrae, f</term>
        <def>filum, aut nervus, aut in medicinis "pars", aut intera, exta</def>
    </entry>
    <entry creationDate="2025-11-08" n="15" language="unspecif">
        <term>su&#772;men, -inis, n</term>
        <def>=mamma</def>
    </entry>
    <entry creationDate="2025-11-08" n="16" language="unspecif">
        <term>cico&#772;nia, cico&#772;niae, f</term>
        <def>stork, or aliquid in imaginem ciconiae formatum</def>
    </entry>
    <entry creationDate="2025-11-09" n="17" language="unspecif">
        <term>&#964;&#8048; &#7988;&#954;&#961;&#953;&#945;</term>
        <def>&#964;&#8056; &#954;&#945;&#964;&#8049;&#963;&#964;&#961;&#969;&#956;&#945;, &#7970; &#964;&#8056; &#946;&#8134;&#956;&#945;</def>
    </entry>
    <entry creationDate="2025-11-15" n="18" language="unspecif">
        <term>congiarium, -i, n.</term>
        <def>=donum</def>
    </entry>
    <entry creationDate="2025-11-16" n="19" language="lat">
        <term>amo</term>
        <def>I love</def>
    </entry>
    <entry creationDate="2025-11-16" n="20" language="unspecif">
        <term>&#954;&#945;&#964;&#945;&#963;&#964;&#8055;&#950;&#969;, -&#958;&#969;</term>
        <def>&#963;&#964;&#8055;&#947;&#956;&#945;&#964;&#945; &#7952;&#957;&#964;&#8055;&#952;&#949;&#957;&#945;&#953; &#960;&#945;&#957;&#964;&#945;&#967;&#8135;</def>
    </entry>
<entry creationDate="2025-11-29" n="21" language="Greek"><term>&#7969; &#954;&#8059;&#963;&#964;&#953;&#962;</term><def>bladder</def></entry><entry creationDate="2025-11-30" n="4" language="grc"><term>&#948;&#8051;&#955;&#964;&#959;&#962; &#948;&#8051;&#955;&#964;&#959;&#962; / tabula</term><def>writing tablet</def></entry><entry creationDate="2025-11-30" n="3" language="lat"><term>flagello, flagellare</term><def>I whip</def></entry><entry creationDate="2025-11-30" n="5" language="grc"><term>&#948;&#959;&#954;&#953;&#956;&#8049;&#950;&#969;</term><def>&#7952;&#958;&#949;&#964;&#8049;&#950;&#969;</def></entry><entry creationDate="2025-11-30" n="6" language="grc"><term>&#956;&#949;&#955;&#8051;&#948;&#951;&#956;&#945;, &#956;&#949;&#955;&#949;&#948;&#8053;&#956;&#945;&#964;&#959;&#962;, n.</term><def>idem ac &#954;&#8134;&#948;&#959;&#962;, &#956;&#8051;&#955;&#951;&#956;&#945;, &#955;&#965;&#960;&#8053;, &#964;&#953; &#952;&#965;&#956;&#959;&#966;&#8049;&#947;&#959;&#957;</def></entry><entry creationDate="2025-11-30" n="7" language="lat"><term>mercor, mercari, mercatus sum</term><def>non &#960;&#969;&#955;&#8051;&#969;, sed &#8032;&#957;&#8051;&#959;&#956;&#945;&#953;</def></entry><entry creationDate="2025-11-30" n="8" language="lat"><term>socrus, socrus, m/f</term><def>&#7953;&#954;&#965;&#961;&#8057;&#962;, ut Hecuba Andromachae.</def></entry><entry creationDate="2025-12-04" n="22" language="grc"><term>&#7957;&#969;&#955;&#959;&#962;, &#7957;&#969;&#955;&#959;&#957;</term><def>day old</def></entry><entry creationDate="2025-12-04" n="22" language="grc"><term>&#946;&#961;&#8161;&#967;&#8049;&#959;&#956;&#945;&#953;, -, -, &#946;&#8051;&#946;&#961;&#8161;&#967;&#945;</term><def>&#956;&#965;&#954;&#8118;&#957;, mugire; cogn. cum barrus, barrire "clamor, clamare"</def></entry><entry creationDate="2025-12-04" n="22" language="grc"><term>&#964;&#961;&#965;&#947;&#8049;&#969;, &#8053;&#963;&#969;...</term><def>=carpere</def></entry><entry creationDate="2025-12-04" n="22" language="grc"><term>&#7969; &#955;&#8059;&#963;&#963;&#8113;, -&#951;&#962;</term><def>=furor</def></entry><entry creationDate="2025-12-04" n="22" language="grc"><term>&#954;&#945;&#964;&#945;&#968;&#949;&#8059;&#948;&#959;&#956;&#945;&#953;</term><def>=&#954;&#945;&#964;&#951;&#947;&#959;&#961;&#8051;&#969;, &#948;&#953;&#945;&#946;&#8049;&#955;&#955;&#969;</def></entry><entry creationDate="2025-12-05" n="23" language="grc"><term>&#8017;&#960;&#959;&#955;&#8055;&#950;&#969;&#957;, -&#959;&#957;&#959;&#962; </term><def>=&#8017;&#960;' &#8000;&#955;&#949;&#8055;&#950;&#969;&#957; = &#956;&#949;&#8055;&#969;&#957;, &#7973;&#963;&#963;&#969;&#957;, &#7952;&#955;&#8049;&#963;&#963;&#969;&#957;</def></entry><entry creationDate="2025-12-12" n="24" language="grc"><term>&#8001; &#948;&#8055;&#959;&#960;&#959;&#962;, -&#959;&#965;</term><def>&#964;&#945;&#947;&#8057;&#962;, &#963;&#964;&#961;&#945;&#964;&#951;&#947;&#8057;&#962;</def></entry></root>
